### PR TITLE
Fix install button issue

### LINKED ISSUE #2: Page Builder install button isn't working
To replicate. Install North in an installation without Page Builder. In the Classic Editor click on the Page Builder tab, click on the Install button in the modal. When I tested, the Install button wasn't functional.

@AlexGStapleton Can you please, pick this one up? Thanks.

### PR DESCRIPTION
**Pull request by AlexGStapleton**
Resolve #2

### CODE REVIEW

**Comment by Misplon** [comment]
Thanks, mate. The modal is displaying normally but the Install button doesn't seem to be functioning for me. Is it functioning for you?

**Comment by AlexGStapleton** [comment]
I just tried this PR again and it's working as expected for me. Is the Install Now button eating the click for you? If so, check the URL of the iframe to ensure it doesn't include `TB_iframe=true`.

**Comment by Misplon** [comment]
My iFrame URL is `/wp-admin/plugin-install.php?tab=plugin-information&amp;plugin=siteorigin-panels&amp;`

Yeah, the click is being eaten. Can you send me a build from Vantage?

**Comment by AlexGStapleton** [comment]
That's strange. Here's a build I just made: [vantage.dev.zip](https://github.com/siteorigin/panels-lite/files/4826397/vantage.dev.zip)

I just tried it in both Chrome and Firefox. Both worked as expected.

**Comment by Misplon** [comment]
@AlexGStapleton I'm having trouble unzipping this file. Please, could you try again? Not sure what the issue is. Perhaps, permissions?

Archive_Utility

**Comment by AlexGStapleton** [comment]
That's odd. Here's a new zip: https://drive.google.com/uc?id=1G_17tfUwRG80m6TndBkvsug24cc4COsm

**Comment by Misplon** [comment]
Follow-up from our Slack chat. Please, test the functionality at Appearance > Home Page. 
Additionally, I seem to be getting a different result (both not working though) in a single site install vs a multi-site install. Perhaps test this PR in both a single and multi-site install.

Thanks!

**Comment by AlexGStapleton** [comment]
Can you please elaborate on the differences you're getting on a multi-site? I had a look over your previous slack messages and I can't seem to see any direct references to this.

**Comment by Misplon** [comment]
On multi-site, the modal was showing the Plugins > Add New screen. I'll test shortly.

**Comment by Misplon** [comment]
Is the tab functionality within the install modal working for you? It's broken for me. The install link works though.

**Comment by AlexGStapleton** [comment]
The tabs are changing but strangely you have to scroll down to see the contents. I see if I can work out how to avoid this.

**Comment by AlexGStapleton** [comment]
I worked out why that's happening - it's due to the removal of `TB_iframe` from the URL. They render the page slightly differently to be more suited to that view. `TB_iframe` was removed to allow for the install button to work. I've looked over the code that handles plugin installs in WordPress (the JS side of things), and the overall lightbox code. I cannot find an alternative solution while also maintaining the previous structure of the iframe. I had another look around and wasn't able to find any other plugins that use this sort of setup so I'm not able to reference other implementation.

I can keep looking for other plugins that do this to reference from, but I'm not very hopeful at this point. Do you want me to keep looking for other plugins that implement this?

**Review by Misplon — APPROVED** [review]

**Comment by Misplon** [comment]
Merging what we have, will log the tabs issue separately.

**Pull request merged**
